name: Windows install test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 6 * * 0'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    defaults:
      run:
        shell: bash -l {0}
    name: Xsar with python ${{ matrix.python-version }} on Windows
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda and create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: xsar
          python-version: ${{ matrix.python-version }}
      - name: Install xsar dependencies
        run: conda install -c conda-forge rasterio">=1.2.6" gdal"==3.3" cartopy_offlinedata dask[array] rioxarray fiona pytest
      - name: Install xsar
        run: |
          pip install -e .
          pip install -r requirements.txt
      - name: Check xsar environment
        run: |
          conda info
          python -V
          conda list rasterio
          conda list gdal
          conda list cartopy
          conda list dask
          conda list fiona
      - name: Testing xsar
        run: pytest



